name: Generate requirements

on: push

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Update requirements
        run: python3 tests/check_pyproject.py

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -z "$(git diff --quiet)" ]; then
            echo "No changes to commit"
            exit 0
          fi

          git add .
          git commit -m ":wrench: Update requirements"
          git push
